In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.contrib import rnn
import pprint
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

/Users/youngji/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
x1_data=[73,93,89,96,73]
x2_data=[80,88,91,98,66]
x3_data=[75,93,90,100,70]
y_data=[152,185,180,196,142]

In [4]:
x1=tf.placeholder(tf.float32)
x2=tf.placeholder(tf.float32)
x3=tf.placeholder(tf.float32)
Y=tf.placeholder(tf.float32)

In [5]:
w1=tf.Variable(tf.random_normal([1]), name='weight1')
w2=tf.Variable(tf.random_normal([1]), name='weight2')
w3=tf.Variable(tf.random_normal([1]), name='weight3')
b=tf.Variable(tf.random_normal([1]), name='bias')

In [6]:
hypothesis=x1*w1+x2*w2+x3*w3+b
cost=tf.reduce_mean(tf.square(hypothesis-Y))

In [7]:
optimizer=tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

In [9]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  61735.355 
Prediction:
 [-56.78249 -88.42113 -76.58916 -85.69564 -70.4549 ]
10 Cost:  68.5331 
Prediction:
 [162.86082 175.63438 183.55771 197.60144 130.965  ]
20 Cost:  67.60206 
Prediction:
 [163.49341 176.4552  184.335   198.45157 131.60309]
30 Cost:  67.23777 
Prediction:
 [163.46349 176.4795  184.32758 198.44714 131.6336 ]
40 Cost:  66.87527 
Prediction:
 [163.43163 176.50136 184.31781 198.44017 131.66223]
50 Cost:  66.51472 
Prediction:
 [163.39983 176.52315 184.30807 198.43318 131.69075]
60 Cost:  66.15614 
Prediction:
 [163.36812 176.54486 184.29834 198.42621 131.7192 ]
70 Cost:  65.79952 
Prediction:
 [163.33652 176.56654 184.28867 198.41928 131.74757]
80 Cost:  65.44479 
Prediction:
 [163.30498 176.58813 184.27898 198.41234 131.77586]
90 Cost:  65.092026 
Prediction:
 [163.27356 176.6097  184.26935 198.40546 131.80411]
100 Cost:  64.74132 
Prediction:
 [163.24222 176.63118 184.25974 198.39856 131.83223]
110 Cost:  64.3922 
Prediction:
 [163.2109  176.65262 184.25012 

1020 Cost:  39.390606 
Prediction:
 [160.6919  178.37888 183.47742 197.83913 134.12029]
1030 Cost:  39.17866 
Prediction:
 [160.66751 178.39557 183.46994 197.83379 134.14215]
1040 Cost:  38.967903 
Prediction:
 [160.64322 178.41223 183.4625  197.82849 134.16397]
1050 Cost:  38.75815 
Prediction:
 [160.61894 178.42885 183.45508 197.82317 134.18571]
1060 Cost:  38.549625 
Prediction:
 [160.59477 178.44542 183.44763 197.81787 134.2074 ]
1070 Cost:  38.342136 
Prediction:
 [160.57063 178.46194 183.44023 197.81258 134.22902]
1080 Cost:  38.135975 
Prediction:
 [160.54662 178.47842 183.43288 197.80731 134.2506 ]
1090 Cost:  37.93073 
Prediction:
 [160.5226  178.49484 183.42549 197.80205 134.2721 ]
1100 Cost:  37.726673 
Prediction:
 [160.49869 178.51125 183.41815 197.79683 134.29355]
1110 Cost:  37.523693 
Prediction:
 [160.47482 178.52759 183.41084 197.79158 134.31494]
1120 Cost:  37.321808 
Prediction:
 [160.45105 178.54391 183.40355 197.78638 134.33629]
1130 Cost:  37.120964 
Prediction:


1990 Cost:  23.356457 
Prediction:
 [158.6092  179.80595 182.8384  197.38365 135.98738]
2000 Cost:  23.231152 
Prediction:
 [158.59045 179.8188  182.83264 197.37955 136.00418]
