In [21]:
import numpy as np  
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[np.newaxis,np.newaxis,:]

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [27]:
x[:,np.newaxis,np.newaxis]

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]],

       [[9]]])

In [25]:
x[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])